# Generated by Django 5.0.2 on 2025-10-17 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_movil_escolar_api", "0002_administradores_delete_profiles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profesores",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "clave_maestro",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("telefono", models.CharField(blank=True, max_length=255, null=True)),
                ("rfc", models.CharField(blank=True, max_length=255, null=True)),
                ("birthdate", models.CharField(blank=True, max_length=255, null=True)),
                ("cubiculo", models.CharField(blank=True, max_length=255, null=True)),
                ("area_inv", models.CharField(blank=True, max_length=255, null=True)),
                ("materias", models.TextField(blank=True, null=True)),
                ("creation", models.DateTimeField(auto_now_add=True, null=True)),
                ("update", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
