# Generated by Django 5.0.2 on 2025-10-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_movil_escolar_api", "0003_profesores"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profesores",
            name="birthdate",
            field=models.DateField(blank=True, null=True),
        ),
    ]
