# Generated by Django 5.0.2 on 2025-11-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_movil_escolar_api", "0005_alumnos"),
    ]

    operations = [
        migrations.AddField(
            model_name="alumnos",
            name="curp",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
