# Generated by Django 5.0.2 on 2025-11-20 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_movil_escolar_api", "0006_alumnos_curp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profesores",
            name="materias",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
